name: happypose
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
#  - nvidia::cudatoolkit==11.3.1
  - python=3.9
  - pip
  - wget
  - python-wget
  - joblib
#  - pytorch::pytorch==1.11.0
  - torchvision==0.12.0
  - ipython
  - ipykernel
  - jupyterlab
#  - notebook
#  - nb_conda_kernels
#  - jupyter_contrib_nbextensions
  - pinocchio
  - rclone
  - pillow
  - ipywidgets
  - selenium
#  - geckodriver
  - firefox
  - assimp
#  - gxx_linux-64
  - ffmpeg
  - bzip2
  - git
  - cmake
  - numpy
  - pip:
      - pybullet
      - distributed
      - jinja2
      - pycollada
      - shapely
      - PyOpenGL
      - Cython
      - glumpy
      - scikit-video
      - scikit-image
      - scikit-learn
      - pywavefront
      - jupyter-client
      - jupyter-core
      - jupyter-server-proxy
      - jupyterlab
      - jupyterlab-server
      - meshcat
      - selenium
      - omegaconf
      - simplejson
      - line_profiler 
      - opencv-python
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - panda3d
      - joblib
      - xarray 
      - pandas
      - matplotlib
      - bokeh
      - plyfile 
      - trimesh 
      - ipdb 
      - panda3d-gltf
      - colorama
      - pyyaml
      - ipykernel
      - scipy
      - pypng
      - h5py 
      - seaborn
      - kornia 
      - pyarrow 
#      - dt_apriltags 
      - open3d
      - structlog
      - imageio
      - progressbar
      - pyyaml
      - psutil
      - webdataset
      - opencv-contrib-python 
      - roma 
      - torchgeometry
